name: ml-project-2-genelipids
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - pandas
  - pycaret[full]
  - scikit-plot
  - pytables
  - numpy
  - matplotlib
  - seaborn
  - scipy
  - scikit-learn
  - tqdm
  - cpuonly # Replace this with cudatoolkit=x.x (personnaly used 12.1) if you have an Nvidia GPU
  - pytorch
  - torchvision
  - torchaudio
